version: "3"
services:
  selenium:
    build:
      dockerfile: ./Dockerfile
    tty: true
    working_dir: "/var/task"
    volumes:
      - "./:/var/task"
      - "./.aws:/root/.aws"

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=5
      - GRID_BROWSER_TIMEOUT=300000
      - GRID_TIMEOUT=300000

  chrome1:
    image: selenium/node-chrome:latest
    container_name: node-chrome1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5901:5901"
    volumes:
      - /dev/shm:/dev/shm
  chrome2:
    image: selenium/node-chrome:latest
    container_name: node-chrome2
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5902:5902"
    volumes:
      - /dev/shm:/dev/shm
  chrome3:
    image: selenium/node-chrome:latest
    container_name: node-chrome3
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5903:5903"
    volumes:
      - /dev/shm:/dev/shm
  chrome4:
    image: selenium/node-chrome:latest
    container_name: node-chrome4
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5904:5904"
    volumes:
      - /dev/shm:/dev/shm
  chrome5:
    image: selenium/node-chrome:latest
    container_name: node-chrome5
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5905:5905"
    volumes:
      - /dev/shm:/dev/shm
  chrome6:
    image: selenium/node-chrome:latest
    container_name: node-chrome6
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5906:5906"
    volumes:
      - /dev/shm:/dev/shm
  chrome7:
    image: selenium/node-chrome:latest
    container_name: node-chrome7
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5907:5907"
    volumes:
      - /dev/shm:/dev/shm
  chrome8:
    image: selenium/node-chrome:latest
    container_name: node-chrome8
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5908:5908"
    volumes:
      - /dev/shm:/dev/shm
  chrome9:
    image: selenium/node-chrome:latest
    container_name: node-chrome9
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5909:5909"
    volumes:
      - /dev/shm:/dev/shm
  chrome10:
    image: selenium/node-chrome:latest
    container_name: node-chrome10
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5910:5910"
    volumes:
      - /dev/shm:/dev/shm
  chrome11:
    image: selenium/node-chrome:latest
    container_name: node-chrome11
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "5911:5911"
    volumes:
      - /dev/shm:/dev/shm